haystack:
  kafka:
     brokers: "haystack.local" # set in /etc/hosts per instructions in haystack-deployment package
     port: 9092 # default Kafka port, rarely overridden, but can be overridden by env variable
     fromtopic: "proto-spans"
     totopic: "" # not used but must be specified as empty for shared YAML parsing to work
  pipe:
    streams:
      replicationfactor: 1
  httppost:
    maxbytes: 1572864 # 1.5 MB
    endpoint: "https://collector.test.expedia.com"
    url: /haystack-spans.json?stream=true&persist=false&multilines=true
    separator: "\n"
    bodyprefix: ""
    bodysuffix: ""
    headers: Content-Type=raw