haystack:
  kafka:
    brokers: "haystack.local"
    port: 9092
    fromtopic: "proto-spans"
    totopic: "detected-secrets"
    threadcount: 2
    sessiontimeout: 15000
  pipe:
    streams:
      replicationfactor: 1
  graphite:
    prefix: "haystack"
    host: "localhost"
    port: 2003
    pollintervalseconds: 300
    queuesize: 10
  secretsnotifications:
    mainbean: "protobufSpanToEmailInKafkaTransformer"  # (method) name of the bean in SpringConfig.java
    actionfactories:
      - "emailerDetectedActionFactory" # (method) name of the bean in SpringConfig.java
    email:
      from: "haystack@expedia.com"
      tos:
        - "haystack-alerts@expedia.com"
      host: "localhost"
      subject: "[Action Required] Security alert in haystack spans!"
