haystack:
  mainbean: "protobufSpanMaskerToKafkaTransformer"  # (method) name of the bean in SpringConfig.java, always needed
  actionfactories: # This section is not needed when masking, because masking just reads from and writes to Kafka
    - "emailerDetectedActionFactory" # (method) name of the bean in SpringConfig.java
  whitelist:
    bucket: "haystack-config"
    key: "secret-detector/whiteListItems.txt"
  email: # This section is only necessary if sending emails
    from: "haystack@expedia.com"
    tos:
      - "haystack-alerts@expedia.com"
    host: "localhost"
    subject: "[Action Required] Security alert in haystack spans!"