haystack:
  kafka:
    brokers: "haystack.local"
    port: 9092
    fromtopic: "json-spans"
    totopic: ""
    threadcount: 1
    sessiontimeout: 15000
  pipe:
    streams:
      replicationfactor: 1
  graphite:
    prefix: "haystack"
    host: "localhost"
    port: 2003
    pollintervalseconds: 300
    queuesize: 10
  secretsnotifications:
    email:
      from: "haystack@expedia.com"
      tos:
        - "haystack-alerts@expedia.com"
      host: "localhost"
      subject: "[Action Required] Security alert in haystack spans!"
