haystack:
  kafka:
     brokers: "haystack.local" # set in /etc/hosts per instructions in haystack-deployment package
     port: 9092 # default Kafka port, rarely overridden, but can be overridden by env variable
     fromtopic: "proto-spans"
     totopic: "json-spans"
  pipe:
    streams:
      replicationfactor: 1
  graphite:
     prefix: "haystack"
     host: "haystack.local" # set in /etc/hosts per instructions in haystack-deployment package
     port: 2003 # default Graphite port, rarely overridden, but can be overridden by env variable
     pollintervalseconds: 60
     queuesize: 10
     sendasrate: true
